-- Grid Bot Database Schema (PostgreSQL)
-- Generated: 2026-02-12
--
-- If you need a fully destructive reset, run:
--   DROP SCHEMA public CASCADE; CREATE SCHEMA public;
-- and then run this file again.

BEGIN;

-- ==============
-- message
-- ==============
CREATE TABLE IF NOT EXISTS message (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message         varchar(255),
  date            date,
  informational   boolean
);

-- ==============
-- trade_instance
-- ==============
CREATE TABLE IF NOT EXISTS trade_instance (
  id              integer PRIMARY KEY,
  name            varchar(255),
  asset           varchar(255),
  wallet_address  varchar(255),
  private_key     varchar(255),
  mail_to         varchar(255),

  -- per-instance runtime settings (DB takes priority over .env)
  telegram_bot_token            varchar(255),
  telegram_chat_id              varchar(255),
  healthchecks_ping_url         varchar(500),
  healthchecks_ping_interval_ms integer,
  bot_tz                        varchar(100),
  hyperliquid_testnet           boolean,

  -- grid config
  pair                         varchar(255),
  target_percent               real,
  margin_percent               real,
  decimal_quantity             integer,
  decimal_price                integer,
  execution_price_min          real NOT NULL DEFAULT 0,
  execution_price_max          real NOT NULL DEFAULT 0,
  reserve_quote_offset_percent real NOT NULL DEFAULT 30,
  reserve_quote_order_id       varchar(20),
  reserve_base_offset_percent  real NOT NULL DEFAULT 30,
  reserve_base_order_id        varchar(20),
  rebuy_profit                 boolean,
  rebuy_percent                integer,
  rebuy_value                  real,
  rebought_value               real,
  rebought_coin                real
);

-- ==============
-- trade_order
-- ==============
CREATE TABLE IF NOT EXISTS trade_order (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buy_order         varchar(255),
  sell_order        varchar(255),
  buy_price         double precision,
  sell_price        double precision,
  quantity          double precision,
  pair              varchar(255),
  trade_instance_id integer,
  last_operation    boolean,
  last_side         varchar(255),
  entry_price       double precision,
  first_profit      double precision,
  CONSTRAINT trade_order_trade_instance_fk
    FOREIGN KEY (trade_instance_id) REFERENCES trade_instance(id)
);

CREATE INDEX IF NOT EXISTS trade_order_instance_idx
  ON trade_order (trade_instance_id);

CREATE INDEX IF NOT EXISTS trade_order_pair_idx
  ON trade_order (pair);

-- ==============
-- trade_profit
-- ==============
CREATE TABLE IF NOT EXISTS trade_profit (
  id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pair                  varchar(255) NOT NULL,
  profit                varchar(255) NOT NULL,
  value                 real NOT NULL,
  date_transaction      timestamp(6),
  date_transaction_utc  timestamp(6),
  target_percent        real,
  price_intermediate    double precision,
  price_final           double precision,
  name                  varchar(255),
  fee                   double precision,
  trade_instance_id     integer,
  CONSTRAINT trade_profit_trade_instance_fk
    FOREIGN KEY (trade_instance_id) REFERENCES trade_instance(id)
);

CREATE INDEX IF NOT EXISTS trade_profit_instance_date_idx
  ON trade_profit (trade_instance_id, date_transaction);

CREATE INDEX IF NOT EXISTS trade_profit_pair_date_idx
  ON trade_profit (pair, date_transaction);

-- ==============
-- trade_cycle
-- ==============
CREATE TABLE IF NOT EXISTS trade_cycle (
  id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pair                  varchar(255) NOT NULL,
  side                  varchar(255) NOT NULL,
  price                 double precision,
  date_transaction      timestamp(6),
  date_transaction_utc  timestamp(6),
  name                  varchar(255),
  trade_instance_id     integer,
  CONSTRAINT trade_cycle_trade_instance_fk
    FOREIGN KEY (trade_instance_id) REFERENCES trade_instance(id)
);

CREATE INDEX IF NOT EXISTS trade_cycle_instance_date_idx
  ON trade_cycle (trade_instance_id, date_transaction);

CREATE INDEX IF NOT EXISTS trade_cycle_pair_date_idx
  ON trade_cycle (pair, date_transaction);

-- ==============
-- open_orders
-- ==============
CREATE TABLE IF NOT EXISTS open_orders (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol          varchar(255) NOT NULL,
  order_id        varchar(255) NOT NULL,
  client_order_id varchar(255) NOT NULL,
  price           double precision,
  orig_qty        double precision,
  executed_qty    double precision,
  side            varchar(255),
  date_created    timestamp
);

CREATE INDEX IF NOT EXISTS open_orders_symbol_idx
  ON open_orders (symbol);

CREATE INDEX IF NOT EXISTS open_orders_order_id_idx
  ON open_orders (order_id);

-- ==============
-- order_history
-- ==============
CREATE TABLE IF NOT EXISTS order_history (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol        varchar(255) NOT NULL,
  order_id      varchar(255) NOT NULL,
  price         double precision,
  qty           double precision,
  quote_qty     double precision,
  commission    double precision,
  date_executed timestamp,
  side          varchar(10),
  usd_qty       double precision,
  deleted_at    timestamp
);

CREATE INDEX IF NOT EXISTS order_history_symbol_date_idx
  ON order_history (symbol, date_executed);

CREATE INDEX IF NOT EXISTS order_history_order_id_idx
  ON order_history (order_id);

COMMIT;
