-- Grid Bot Database Schema (PostgreSQL)
-- Generated: 2026-02-12
--
-- If you need a fully destructive reset, run:
--   DROP SCHEMA public CASCADE; CREATE SCHEMA public;
-- and then run this file again.

BEGIN;

-- ==============
-- message
-- ==============
CREATE TABLE IF NOT EXISTS message (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message         varchar(255),
  date            date,
  informational   boolean
);

-- ==============
-- trade_instance
-- ==============
CREATE TABLE IF NOT EXISTS trade_instance (
  id              integer PRIMARY KEY,
  name            varchar(255),
  wallet_address  varchar(255),
  private_key     varchar(255),
  mail_to         varchar(255)
);

-- ==============
-- trade_config
-- ==============
CREATE TABLE IF NOT EXISTS trade_config (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pair                varchar(255),
  entry_price         double precision,
  exit_price          double precision,
  target_percent      real,
  margin_percent      real,
  usd_transaction     real,
  decimal_quantity    integer,
  decimal_price       integer,
  trade_instance_id   integer NOT NULL,
  name                varchar(255),
  rebuy_profit        boolean,
  order_block_price   double precision,
  order_block_id      varchar(20),
  rebuy_percent       integer,
  rebuy_value         real,
  rebought_value      real,
  rebought_coin       real,
  execution_price_min real,
  execution_price_max real,
  CONSTRAINT trade_config_trade_instance_fk
    FOREIGN KEY (trade_instance_id) REFERENCES trade_instance(id)
);

CREATE INDEX IF NOT EXISTS trade_config_instance_idx
  ON trade_config (trade_instance_id);

CREATE INDEX IF NOT EXISTS trade_config_pair_idx
  ON trade_config (pair);

-- ==============
-- trade_order
-- ==============
CREATE TABLE IF NOT EXISTS trade_order (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buy_order         varchar(255),
  sell_order        varchar(255),
  buy_price         double precision,
  sell_price        double precision,
  quantity          double precision,
  pair              varchar(255),
  trade_instance_id integer,
  last_operation    boolean,
  last_side         varchar(255),
  entry_price       double precision,
  first_profit      double precision,
  CONSTRAINT trade_order_trade_instance_fk
    FOREIGN KEY (trade_instance_id) REFERENCES trade_instance(id)
);

CREATE INDEX IF NOT EXISTS trade_order_instance_idx
  ON trade_order (trade_instance_id);

CREATE INDEX IF NOT EXISTS trade_order_pair_idx
  ON trade_order (pair);

-- ==============
-- trade_profit
-- ==============
CREATE TABLE IF NOT EXISTS trade_profit (
  id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pair                  varchar(255) NOT NULL,
  profit                varchar(255) NOT NULL,
  value                 real NOT NULL,
  date_transaction      timestamp(6),
  target_percent        real,
  price_intermediate    double precision,
  price_final           double precision,
  name                  varchar(255),
  fee                   double precision,
  trade_instance_id     integer,
  CONSTRAINT trade_profit_trade_instance_fk
    FOREIGN KEY (trade_instance_id) REFERENCES trade_instance(id)
);

CREATE INDEX IF NOT EXISTS trade_profit_instance_date_idx
  ON trade_profit (trade_instance_id, date_transaction);

CREATE INDEX IF NOT EXISTS trade_profit_pair_date_idx
  ON trade_profit (pair, date_transaction);

-- ==============
-- open_orders
-- ==============
CREATE TABLE IF NOT EXISTS open_orders (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol          varchar(255) NOT NULL,
  order_id        varchar(255) NOT NULL,
  client_order_id varchar(255) NOT NULL,
  price           double precision,
  orig_qty        double precision,
  executed_qty    double precision,
  side            varchar(255),
  date_created    timestamp
);

CREATE INDEX IF NOT EXISTS open_orders_symbol_idx
  ON open_orders (symbol);

CREATE INDEX IF NOT EXISTS open_orders_order_id_idx
  ON open_orders (order_id);

-- ==============
-- order_history
-- ==============
CREATE TABLE IF NOT EXISTS order_history (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol        varchar(255) NOT NULL,
  order_id      varchar(255) NOT NULL,
  price         double precision,
  qty           double precision,
  quote_qty     double precision,
  commission    double precision,
  date_executed timestamp,
  side          varchar(10),
  usd_qty       double precision,
  deleted_at    timestamp
);

CREATE INDEX IF NOT EXISTS order_history_symbol_date_idx
  ON order_history (symbol, date_executed);

CREATE INDEX IF NOT EXISTS order_history_order_id_idx
  ON order_history (order_id);

COMMIT;
